export const extensionIdeas = [
  { id: "inline-edit-related", name: "Inline edit on related lists", points: 90180, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdlpwUAB" },
  { id: "default-sort", name: "Default sort order", points: 36820, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdlwEUAR" },
  { id: "export", name: "Export from the list", points: 34840, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdhcKUAR" },
  { id: "auto-refresh", name: "Refresh the list on a timer", points: 25940, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdWYUUA3" },
  { id: "real-count", name: "Real record count past 50+", points: 16460, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdoZOUAZ" },
  { id: "sort-activities", name: "Sort activities", points: 12790, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdhucUAB" },
  { id: "highlight", name: "Conditional highlighting", points: 12680, url: "https://ideas.salesforce.com/s/idea/a0B8W00000Gdd1qUAB" },
  { id: "parent-columns", name: "Parent fields as columns", points: 11940, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdlKJUAZ" },
  { id: "kanban-over-200", name: "Kanban past 200 cards", points: 11880, url: "https://ideas.salesforce.com/s/idea/a0B8W00000Gdl7NUAR" },
  { id: "row-count", name: "Choose how many related rows show", points: 11070, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdVoBUAV" },
  { id: "quick-filters", name: "Quick filters", points: 9560, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdeerUAB" },
  { id: "totals", name: "Total a related list", points: 9240, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdeHgUAJ" },
  { id: "mass-delete-rows", name: "Delete selected records", points: 7770, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdcDiUAJ" },
  { id: "kanban-columns", name: "Choose Kanban columns", points: 7420, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdbJAUAZ" },
  { id: "kanban-lost", name: "Lost opportunities on the Kanban", points: 7320, url: "https://ideas.salesforce.com/s/idea/a0B8W00000Gdn7EUAR" },
  { id: "current-user", name: "Filter by the current user", points: 7260, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdfihUAB" },
  { id: "more-related-columns", name: "More than 10 related columns", points: 7150, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdicWUAR" },
  { id: "recycle-bin", name: "Views in the Recycle Bin", points: 6940, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdhVKUAZ" },
  { id: "pinned-list", name: "Keep the pinned list", points: 6730, url: "https://ideas.salesforce.com/s/idea/a0B8W00000Gdj3sUAB" },
  { id: "hover", name: "Hover a cell for more of the record", points: 6570, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdeZMUAZ" },
  { id: "following", name: "Filter to records you follow", points: 6320, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdYg9UAF" },
  { id: "change-owner", name: "Change owner from the list", points: 6120, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdlDsUAJ" },
  { id: "delete-views", name: "Delete custom list views", points: 6100, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GddBvUAJ" },
  { id: "more-list-columns", name: "More than 15 list columns", points: 5620, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdiYXUAZ" },
  { id: "kanban-default", name: "Open Opportunities on a Kanban", points: 5510, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdWurUAF" },
  { id: "campaign-company", name: "Sort campaign members by company", points: 5200, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdjlYUAR" },
  { id: "kanban-no-record-type", name: "Kanban without record-type grouping", points: 5160, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GddKhUAJ" },
  { id: "select-over-200", name: "Select more than 200 records", points: 5000, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdYJqUAN" },
  { id: "account-team", name: "My account team and my accounts", points: 4910, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdZrFUAV" },
  { id: "kanban-colors", name: "Kanban card colors", points: 4800, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdkZIUAZ" },
  { id: "inline-opportunity", name: "Inline edit Opportunity Amount and Stage", points: 4700, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdVtBUAV" },
  { id: "column-widths", name: "Remember column widths", points: 4590, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdYp0UAF" },
  { id: "more-filters", name: "More than 10 filters", points: 4400, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdiglUAB" },
  { id: "row-actions", name: "Inline edits and row actions", points: 4220, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GddEpUAJ" },
  { id: "formula-filters", name: "Quick-filter formula fields", points: 4140, url: "https://ideas.salesforce.com/s/idea/a0B8W00000Gdfx3UAB" },
  { id: "hide-empty", name: "Hide an empty related list", points: 3960, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GddvYUAR" },
  { id: "my-tasks", name: "Keep My Tasks selected", points: 3840, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdbieUAB" },
  { id: "kanban-alerts", name: "Custom alerts on Kanban cards", points: 3520, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdcLEUAZ" }
];

export const packageIdeas = [
  { id: "translations", name: "Translated names for the packaged lists", points: 16440, url: "https://ideas.salesforce.com/s/idea/a0B8W00000Gdb9YUAR" },
  { id: "dynamicFilters", name: "List accepts filter values from the page", points: 3650, url: "https://ideas.salesforce.com/s/idea/a0B8W00000Gdo6ZUAR" },
  { id: "childTotal", name: "Maintained count and total of child records", points: 3250, url: "https://ideas.salesforce.com/s/idea/a0B8W00000GdfetUAB" }
];
